"""Data models (ORM + Pydantic) for VisaForge."""
from .orm import (
    Base,
    UserProfile,
    EligibilityResult,
    RoutePlan,
    RouteStep,
    CaseDocument,
    ScholarshipSource,
    ScholarshipEntry,
    SavedScholarship,
    CuratedSource,
    FetchLog,
)
from .user import User, UserRole
from .schemas import (
    ProfileIn,
    RuleEvaluation,
    EligibilityReport,
    RouteStepDTO,
    RoutePlanDTO,
    ScholarshipDTO,
    SourceConfig,
    IngestionResult,
    LLMMessage,
    LLMResponse,
)

__all__ = [
    "Base",
    "User",
    "UserRole",
    "UserProfile",
    "EligibilityResult",
    "RoutePlan",
    "RouteStep",
    "CaseDocument",
    "ScholarshipSource",
    "ScholarshipEntry",
    "SavedScholarship",
    "CuratedSource",
    "FetchLog",
    "ProfileIn",
    "RuleEvaluation",
    "EligibilityReport",
    "RouteStepDTO",
    "RoutePlanDTO",
    "ScholarshipDTO",
    "SourceConfig",
    "IngestionResult",
    "LLMMessage",
    "LLMResponse",
]
